# Generated by Django 4.0.5 on 2022-06-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='drink_category',
            field=models.ManyToManyField(to='product.drink'),
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='menu_category',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='menu_drink',
        ),
    ]
